# !/usr/bin/env python
# -*- coding: utf-8 -*-
"""常量定义。"""

# 超时与等待
INPUT_TEXT_WAIT_TIME = 1
DEFAULT_IDLE_TIME = 0.5
DEFAULT_SLIDE_TIME = 0.3
MAX_TIMEOUT = 60
DEFAULT_TIMEOUT = 5
WAIT_FOR_INSTALL_TIME = 3
FAST_SWIPE_TIME = 0.25
SWIPE_INTERVAL = 0.5

# 手势参数
NAV_GESTURE_SPEED = 8000
DEFAULT_SWIPE_DURATION = 0.5
DEFAULT_DOUBLE_CLICK_INTERVAL = 0.15
DEFAULT_LONG_CLICK_INTERVAL = 1

# 内部常量
FULL_DRIVER_TMP_KEY = "_tmp_full_uidriver"
